#!/bin/sh

# This little script shows how I'm handling input in a single loop without blocking or using jobs.

# sets the terminal to not echo input
# and to only wait for $TURN_DURATION tenths of a second
# when waiting for input.
stty -icanon -echo time 20 min 0

# Game loop
while true; do
  echo 'BEGIN'
  key=$(dd bs=1 count=1 2> /dev/null)

  if [ ! "$key" = '' ]; then
    echo "You pressed: $key"
  fi
  echo 'END'
done
